language: node_js

node_js:
- '7'
- '6'
- '8'

git:
  depth: 1

branches:
  only:
  - master

env:
  global:
  - CXX=g++-4.8

install:
  npm i

script:
  npm run build && npm run test && npm run test:localGit